sudo: required
language: java
jdk:
  - openjdk8

env:
  global:
    - COMMIT=${TRAVIS_COMMIT::7}

services:
  - docker

script: "mvn clean package -Dmaven.test.skip=true"

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - export TAG=`if [ "$TRAVIS_BRANCH" == "main" ]; then echo "latest"; else echo $TRAVIS_BRANCH; fi`
  - export IMAGE_NAME=gongsir0630/wx-java-miniapp
  - docker build -t $IMAGE_NAME:$COMMIT .
  - docker tag $IMAGE_NAME:$COMMIT $IMAGE_NAME:$TAG
  - docker push $IMAGE_NAME:$TAG

branches:
  only:
    - main

notifications:
  email:
    - gongsir0630@gmail.com