# dev环境配置文件
spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://gongsir.club:3306/wxapp
        username: root
        password: admin1234
    # redis 配置信息: 在本地安装redis
    redis:
      host: 127.0.0.1
      port: 6379
      database: 0
      password: admin1234
      timeout: 3000
      jedis:
        pool:
          max-idle: 8
          max-wait: -1

---
# 服务启动的端口号
server:
  port: 8081

---
logging:
  level:
    org.springframework.web: info
    com.github.gongsir0630.wxapp: debug